@echo off
CLS
:menu1
ECHO MENU PRINCIPAL
ECHO A) Sig. Menu
ECHO B) Salir
CHOICE /C:AB
IF ERRORLEVEL 2 EXIT

ECHO MENU SECUNDARIO
ECHO A) Contenido de C:\
ECHO B) Version de DOS
ECHO C) Menu Principal
CHOICE /C:ABC
IF ERRORLEVEL 3 GOTO menu1
IF ERRORLEVEL 2 VER
IF ERRORLEVEL 1 DIR C:\
